---
title: "linear-regression-rcourse2"
author: "busra nur darendeli"
date: "15 Mart 2019"
output: html_document
---

#Linear Regression

```{r message=FALSE, warning=FALSE}
data<-read.csv("KR.GECIK.txt")

str(data)
summary(data)

attach(data)
plot(GECIKEN, MIKTR, ylim=c(0,150), xlab="Geciken Kredi Taksidi", ylab="Çekilen Kredi Miktarı", main="Regresyon", pch=19)

```

```{r}
REG<- lm(MIKTR~GECIKEN)
REG
#miktar ve geciken arasında bir denklem kuruyor, geciken taksit üzerinden miktar tahmini yapıyor

summary(REG)

#residual = artıkları topladığımız kısım
#intercept beta0 beta1 geciken değeri bizim denklemimiz miktar = beta1*geciken+beta0
#t değerleri de anlamlılık anlamında iyi duruyor *, ***
#model anlamlı mı küçük bir deper 1.49e-12
#geciken gerçekten miktarı açıklıyor mu bunun cevabı rsquare değeri 0.6511 
```

```{r}
predict(REG, newdata=data.frame(GECIKEN=c(40,45,70)))
```

##güven aralığı
```{r}
confint(REG)

 
#gecikenin güven aralığının 97.5 ve %2.5luk arasında fena olmayan değerler vermis 

```

##sıfır ortalama varsayımının kontrolü
```{r}
sum(residuals(REG))/50


#H0 ve H1 hipotezini kullanmıştıki p değerin küçük çıkması gerek dolayısıyla H0'ı sağlıyor diyebiliriz. 
```

##sabit varyans sayımı
```{r}
library(lmtest)
bptest(REG)

#p değeri 0.05'ten düşük olanlar daha iyi kabul edilir. H0 hataların varyansa eşit olması gerek yani homojenliğin kabul edilmesi gerek. burada %93'lük bir değerlendirmede %95 olması gerek o yüzden homojenlik testinden geçemedi
```

##normallik varsayımı
```{r}
shapiro.test(residuals(REG))

#bu testten geçti
```

##otokorelasyon varsayımı
```{r}
dwtest(REG, alternative="two.sided")

#%95 güven aralığını sağlayamadı
#Şartların hepsini sağlamak zorundayız. 

```


#Çoklu Doğrusal Regresyon Analizi

```{r}
data<-read.csv("B.HACM.txt")

summary(data)

#bağımlı değişken büyüme hacmi , bağımsız değişkende güven ve firma sayısı. bankanın büyüme hacminde bankaya duyulan güven indeksi ve bankanın çalıştığı firma sayısı etkli mi bunu inceliyoruz. 

#büyüme hacmi = beta0+ beta1*güven indeksi+ beta2*firma sayısı

```

```{r}
plot(data[,-1], pch=19, col="blue", main="BUYUME HAC-FIRMA SAY- GUVEN IND(Scatterplot)")

#1.satırı çıkarma sebebimiz ID satırı gitsin diye
```

```{r}
MREG<-lm(data$BUYUME.H~data$GUVEN.IND+data$FIRMA.S)
#~ eşittir gibi kullanılıyor

summary(MREG)
#beta0 = -57 beta1=5.7 beta2 = 0.33
#* %99 güven aralığına denk gelir
#modelin doğruluğu anlamında p-value 2.2e-16
#Rsquare bağımlı değşken ve bağımsız değişkenlerin alakasını veriyor 0.94

```

##¦sıfır ortalama varyansı

```{r}
sum(residuals(MREG))/50

#p-value kçük h0 h1 i sağlar
```

##sabit varyans varsayımı

```{r}
bptest(MREG)

#p-value 0.05ten küçük olması gerek 0.3 neredeyse kabul edilemez
```

##normallik varsayımı

```{r}
shapiro.test(residuals(MREG))


```

##otokorelasyon varsayımı

```{r}
dwtest(MREG, alternative="two.sided")

```

